apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: github
spec:
  type: git
  params:
    - name: revision
      value: tekton-app
    - name: url
      value: https://github.com/ZotakBmm/public-app